# Transformers and estimators

There are two kinds of pipeline objects
- transformers (i.e. normalizing or standardizing)
- estimators (i.e. fitting a model)

To implement 


Lets first take a look at a transformer that adds a number to each row of a dataset:

- transform - applies the transformation
- inverse transform - reverse the transformation

In [7]:
from sklearn.base import TransformerMixin, BaseEstimator

class Adder(TransformerMixin, BaseEstimator):
    def __init__(self, num):
        self.num = num

    def transform(self, x):
        return x + np.full(shape=x.shape, fill_value=self.num)
    
    def inverse_transform(self, x):
        return x - np.full(shape=x.shape, fill_value=self.num)
    
adder = Adder(4)

x = np.array([0, 2 ,4])

train = adder.transform(x)

train

array([4, 6, 8])

In [8]:
adder.inverse_transform(train)

array([0, 2, 4])

## Estimators

- fit
- predict

In [4]:
from sklearn.base import BaseEstimator, RegressorMixin


class NaiveRegressor(BaseEstimator, RegressorMixin):
    def __init__(self):
        pass
        
    def fit(self, x, y):
        self.pred = np.mean(y)
        return self
        
    def predict(self, x):
        return np.full(shape=x.shape, fill_value=self.pred)
    
reg = NaiveRegressor()

reg.fit(x=np.zeros((50)), y=np.random.uniform(size=50))

reg.predict(x=np.array([0, 1]))

array([0.5793159, 0.5793159])