In [1]:
import numpy as np

In [2]:
W = np.random.randn(4, 3)
X = np.random.randn(3, 2)
Z = W.dot(X)

In [3]:
W

array([[-2.64081973, -1.04194169,  0.56521301],
       [ 0.4961925 ,  0.67071817, -2.10767979],
       [-0.18266997,  0.85568614,  1.72815417],
       [-0.17681187,  0.07846215, -0.68642891]])

In [4]:
X

array([[ 0.4532298 , -1.01912815],
       [ 0.87048031, -0.78447653],
       [ 1.45740071,  1.17077784]])

In [5]:
Z

array([[-1.28014608,  4.1704514 ],
       [-2.26299784, -3.4994712 ],
       [ 3.18067958,  1.53818303],
       [-1.01223863, -0.68501352]])

In [6]:
W[0, 0] * X[0, 0] + W[0, 1] * X[1, 0] + W[0, 2] * X[2, 0]

-1.2801460768437924

In [7]:
sum([i*j for (i, j) in zip(W[0, :], X[:, 0])])

-1.2801460768437924

In [8]:
sum([i*j for (i, j) in zip(W[0, :], X[:, 1])])

4.170451399423806