In [1]:
import numpy as np

In [20]:
W = np.random.randn(4, 3)
X = np.random.randn(3, 2)
Z = W.dot(X)

In [21]:
W

array([[-0.95094322, -1.3603969 , -0.04419692],
       [-0.18075479,  0.34879543, -0.08166952],
       [ 0.75419405, -0.64509478,  1.65910435],
       [ 0.03507914, -0.68783935,  0.35163672]])

In [22]:
X

array([[ 0.12433141,  0.34566082],
       [-1.17788267, -1.68832376],
       [-0.24032746, -0.49147975]])

In [23]:
Z

array([[ 1.49477756,  1.98980849],
       [-0.41368617, -0.61122055],
       [ 0.45488764,  0.534408  ],
       [ 0.73004753,  1.00059868]])

In [25]:
Z = np.zeros((4, 2))
Z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
W[0, 0] * X[0, 0] + W[0, 1] * X[1, 0] + W[0, 2] * X[2, 0]

1.4947775578813882

In [36]:
sum([i*j for (i, j) in zip(W[0, :], X[:, 0])])

1.4947775578813882

In [37]:
sum([i*j for (i, j) in zip(W[0, :], X[:, 1])])

1.9898084878294098