In [1]:
import numpy as np

In [1]:
# generate some random data
W = np.random.randn(4, 3)
X = np.random.randn(3, 2)
# calculate the dot product using numpy
Z = W.dot(X)

In [2]:
W

array([[-0.60299206,  0.78735229,  0.30762302],
       [ 0.21039421, -2.25463027,  0.58420845],
       [ 1.37997045,  1.47797672, -0.02425968],
       [-1.02904189,  0.06614116, -1.88648938]])

In [3]:
X

array([[-0.30538643, -0.97350094],
       [-0.3683484 ,  0.17693506],
       [ 0.33476347,  0.77609825]])

In [4]:
Z

array([[-0.00289341,  0.96506925],
       [ 0.96180956, -0.15033896],
       [-0.97395586, -1.10072451],
       [-0.34163529, -0.45062516]])

In [5]:
# we can reproduce the dot-product calculation
# for the first element of Z
W[0, 0] * X[0, 0] + W[0, 1] * X[1, 0] + W[0, 2] * X[2, 0]

-0.002893413870089595

In [6]:
# we can do this in a more vectorized way
sum([i*j for (i, j) in zip(W[0, :], X[:, 0])])

-0.002893413870089595

In [8]:
# calculating the second element 
sum([i*j for (i, j) in zip(W[0, :], X[:, 1])])

0.9650692450539503